### ISSUE TITLE
What is the Authorization  of it?

### ISSUE THREAD

**Issue by coolking70** [linuzilla/ubuntu1604-cloud9base#1]
I just pull and run it,but when I try to get in it ask for username and password that I don't know at all

**Comment by linuzilla** [comment]
Find username and password in files/cloud9.conf, in which, the default username and password is  cloud9 and c9passwd
This image did not provide a way to change default username and password at run time. maybe you can try another image instead:

https://github.com/linuzilla/docker-cloud9ide

and you can change username and password at run time,
Something like:

docker run --name cloud9 -p 8181:8181 -e C9USERNAME=username -e C9PASSWORD=password -e C9USERID=1000  -v /your/workspace:/workspace -d linuzilla/cloud9ide

**Comment by coolking70** [comment]
thanks
